TEXT = (
    "The Book of the Nem. "
    "Another Testament of Jesus Christ. "
    "From the Nem People. "
    "Accounts Written by the Hands of Nem Prophets and Recordkeepers. "
    "Taken from the Written Records of the Nem, the People of the Spirit. "
    "\n\n"
    "The Book of the Nem is written to the descendants of the Lamanites of the "
    "Book of Mormon, who are a remnant of the House of Israel, and also to the "
    "descendants of the Nem, and to the Gentiles, by way of commandment, and also "
    "by the spirit of prophecy and of revelation, to the convincing of all that "
    "Jesus Christ is the Son of God, the Savior of all mankind throughout the world. "
    "\n\n"
    "It is a record of the people of Hagoth, the shipbuilder, and the people of "
    "Corianton, the son of Alma the younger, who traveled into the Land Northward "
    "to escape the wickedness of the Nephites and secret combinations of the "
    "Gadianton Robbers who were beginning to spread across the land. It is to show "
    "unto the remnant of the House of Israel what great things the Lord hath done "
    "for their fathers and brothers; and that they may know the covenants of the "
    "Lord, that they are not cast off forever, and also to the convincing of the "
    "Gentiles that Jesus is the Christ, the Eternal God, manifesting himself unto "
    "all nations, including the ancestors of the Nem long ago. And now, if there "
    "are faults in this record, they are the mistakes of men; wherefore, condemn "
    "not the things of God. Search these records, ponder, and pray that Jesus "
    "Christ may reveal the truth of it unto you by the power of the Holy Ghost, "
    "for by the power of the Holy Ghost, ye may know the truth of all things. "
    "See Moroni chapter ten, verses three through five. "
    "\n\n"
    "The purpose of this record is to assist in the gathering of the House of "
    "Israel, to bring to light the words of Christ given to His other sheep, to "
    "prepare the Remnant of Joseph to rise up, and the Remnant of Jacob to return; "
    "that they may fulfill their covenants, build the New Jerusalem, and establish "
    "Zion in these last days before the return of our Lord and Savior, Jesus "
    "Christ, in glory."
)
